version: '3'

services:
  muzmatch-messages:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 2000:1975
    working_dir: /usr/src/app
    container_name: muzmatch-messages
    command: npm start
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"
